spring:
  application:
    name: kairos-service-registry

server:
  port: 8761

kairos:
  serviceRegistry:
    username: serviceregistry
    password: 'kairos123sr'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: 'http://${kairos.serviceRegistry.username}:${kairos.serviceRegistry.password}@localhost:8761/eureka'