services:
  database:
    container_name: "postgres-kairos"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5440:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_connections=901"]

  database_v2:
    container_name: "postgres-kairos-v2"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5441:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_connections=901"]

  rabbitmq:
    container_name: "rabbitmq-kairos"
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672" # Porta padrão para conexões AMQP
      - "15672:15672" # Porta para o painel de administração web
    environment:
      RABBITMQ_DEFAULT_USER: "local_user"
      RABBITMQ_DEFAULT_PASS: "local_password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
