services:
  database:
    container_name: "postgres-kairos"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5440:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d	
    command: ["postgres", "-c", "max_connections=901"]
