server:
  port: 8088
  servlet:
    context-path: '/kairos-market/'

spring:
  application:
    name: kairos-market-service
  datasource:
    url: jdbc:postgresql://localhost:5440/kairos_market
    username: local_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true

    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always

logging:
  level:
    town.kairos: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

kairos:
  api:
    url:
      authuser: 'http://kairos-authuser-service/kairos-authuser'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost