server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/kairos_authuser
    username: local_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true

    show-sql: true
    open-in-view: false