spring:
  application:
    name: kairos-authuser-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: kairos-config-server
      username: configserver
      password: 'kairos123cs'
