kairos:
  serviceRegistry:
    username: serviceregistry
    password: "kairos123sr"

eureka:
  client:
    service-url:
      defaultZone: "http://${kairos.serviceRegistry.username}:${kairos.serviceRegistry.password}@localhost:8761/eureka"
  instance:
    hostname: localhost
