kairos:
  serviceRegistry:
    username: serviceregistry
    password: "kairos123sr"
  auth:
    jwtSecret: aArdRixQqS1xAE6wFs45sFnhTos3WoJvOUNKhNcjR04XzqTKOxaEEr0mzrIXQBUOEY5UvIYpnM1jdcA1MNgQ3A==
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone: "http://${kairos.serviceRegistry.username}:${kairos.serviceRegistry.password}@localhost:8761/eureka"
  instance:
    hostname: localhost
