server:
  port: 8888

spring:
  application:
    name: kairos-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adspacheco/kairos
          search-paths: envs
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost